### ISSUE TITLE
Java Version on Windows

### ISSUE THREAD

**Issue by sils1297** [myint/language-check#10]
Hey, seems language-check has something against java version 1.8? You claim your setup takes care of gettting the right java stuff. Here's what we're experiencing:

https://ci.appveyor.com/project/sils1297/coala/build/1.0.1079/job/uwhqxai01o767g6i#L174

**Comment by myint** [comment]
I'm not familiar with Windows, but pull requests are welcome.

**Comment by myint** [comment]
http://help.appveyor.com/discussions/suggestions/365-install-jdk

**Comment by sils1297** [comment]
THanks, actually I already tried adjusting the PATH so that the right java
version was taken in this commit
https://github.com/coala-analyzer/coala/commit/ad7e37a0cdcd992c50e53b5442139a8be0c5c352
- however it still fails on 64 bit version builds. May indeed be an
AppVeyor issue.


2015-07-08 17:12 GMT+02:00 Steven Myint <notifications@github.com>:
