### ISSUE TITLE
Has anyone tried with LT Version 3.2 yet?

### ISSUE THREAD

**Issue by vfulco** [myint/language-check#20]
New to the code set and initial download indicates it is using 2.7.  I am on Ubuntu 15.04.  TIA.

**Comment by myint** [comment]
I don't have access to a machine with Java 8, which LanguateTool 3.2 requires. But if you test 19f027e987091227a4ac13094c7ae0bf05b88037 and find it works, I can enable 3.2.

**Comment by jasonm** [comment]
Is it possible to test on JDK8 with the following in `.travis.yml` ?

```yaml
jdk:
  - oraclejdk8
```

Per https://docs.travis-ci.com/user/languages/java#Testing-Against-Multiple-JDKs

**Comment by myint** [comment]
@jasonm, I think that only works if the `language` is `java`. In this project, the `language` is `python` and we test against multiple versions of it.
