### ISSUE TITLE
Not able to build language-check using setuptools in python2.7.

### ISSUE THREAD

**Issue by sjose1x** [myint/language-check#21]
from setuptools import setup, find_packages
setup(
    name='name',
    version='0.0.1',
    description=' TA',
    long_description=DESCRIPTION,
    license='Proprietary License',
    author='',
    author_email='',
    packages=find_packages(),
    install_requires=[
        "language-check==0.7.1",
        "3to2==1.1.1",
    ],

python setup.py install #Fails

**Comment by myint** [comment]
As far as I know, `3to2` must be installed beforehand. Only then can you install `language-check`. Otherwise, `setup.py` won't have access to `3to2`.
