### ISSUE TITLE
What is the purpose of `enabled` ?

### ISSUE THREAD

**Issue by AbdealiJK** [myint/language-check#23]
I notice that the language tool docs state that (http://wiki.languagetool.org/http-server) the reasno `enabled` exists is because if you want to enable only certain rules, you set `enabledOnly=True` and give a list of rules to be `enabled` (all other rules are disabled)

It doesnt seem to be working in `language-check`.
I checked the code and here the `enabledOnly` is never being sent (https://github.com/myint/language-check/blob/master/language_check/__init__.py#L259)

So - the `--enabled` arg is pretty much useless, as all rules are enabled.

**Comment by myint** [comment]
Is `--enable` really useless right now? I thought maybe LanguageTool would have some default rules and some more experimental rules that are not enabled by default.

In any case, I can add an `--enabled-only` option.

**Comment by AbdealiJK** [comment]
Well, based on some tests i ran - I couldnt find one which was disabled by default - Hence I tried searching for the documentation and came across the enabledOnly.

Adding `--enabled-only` would be awesome !

**Comment by myint** [comment]
It should be there now. I'll make a new release shortly.

Thanks for pointing out this parameter.

**Comment by AbdealiJK** [comment]
Awesome ! thanks for the quick response time :)
