### ISSUE TITLE
How can language-check connect to a remote languagetool server?

### ISSUE THREAD

**Issue by fekete-robert** [myint/language-check#4]
Hi, 

Is it possible to configure language-check not to start a local languagetool server, but connect to a remote, already running instance?
I haven't found it in the docs, and I'm not a programmer, so couldn't figure it out from the code.

The idea would be to run a central languagetool server, and my clients would connect to it using language-check (and various languagetool plugins).

Kind Regards, 

Robert Fekete

**Comment by myint** [comment]
That feature does not currently exist.

**Comment by sfbrian** [comment]
I'd like to see this as well. Does this only currently support local instances of LanguageTool?

**Comment by myint** [comment]
Correct, it currently only supports the local instance that gets started by `language-check` itself.

**Comment by myint** [comment]
This is closed by #34.
