### ISSUE TITLE
_server_is_alive checks only for local server

### ISSUE THREAD

**Issue by SankethPinchMe** [myint/language-check#41]
The way class method _server_is_alive is written it only checks for the local server. When LanguageTool instance is created with a remote server _server_is_alive fails to check the remote server and starts a local server.

**Comment by myint** [comment]
Thanks for the report! Could you check if 7a541bf0b390f0525233bec8749e2535fd59875a fixes the problem?

Thanks

**Comment by 2ank3th** [comment]
Yes, this fixes the problem. I was working on a fix myself but it included a check if the remote server is working or not. 

Do you still want me to work on that? 

Thanks

**Comment by myint** [comment]
@2ank3th Sure, I think a check of the remote server would be useful. Thanks!
