### ISSUE TITLE
Can not use LanguageTool-3.7

### ISSUE THREAD

**Issue by pbms** [myint/language-check#42]
Using "pip install" the language-check, the default LanguageTool is V3.2. When I try to replace the old version by LanguageTool-3.7, an error message occurs. How to use the latest version of  LanguageTool? Thanks.

**Comment by myint** [comment]
I think #15 discusses this. Another option is to try updating the [latest version specification](https://github.com/myint/language-check/blob/47ca7750629ce7f50f73143c62d87705a37a93f6/download_lt.py#L31).

**Comment by myint** [comment]
What is the error message?

**Comment by pbms** [comment]
The error message is: 
PathError: can't find languagetool-standalone in 'C:\\Users\\m\\Anaconda34\\lib\\site-packages\\language_check\\LanguageTool-3.7'. 

I follow your instruction in pypi: The installation process should take care of downloading LanguageTool (it may take a few minutes). Otherwise, you can manually download LanguageTool-stable.zip and unzip it into where the language_check package resides.

Then, I download it and replace it.

**Comment by pbms** [comment]
BTW, another error message is:

Error: Error: Could not find or load main class org.languagetool.server.HTTPServer

**Comment by myint** [comment]
So what *is* in `C:\Users\m\Anaconda34\lib\site-packages\language_check\LanguageTool-3.7`?

**Comment by pbms** [comment]
Please ignore the error message your above-mentioned. I think this message is not caused by language-check.
