### ISSUE TITLE
Missing Grammar check rules- Missing space between full stop and first word of the next sentence

### ISSUE THREAD

**Issue by nnayar** [myint/language-check#48]
I am testing out for a few grammatical error conditions and not getting the desired results:

Missing space between full stop and first word of the next sentence: 
Example:
Input:      capitalizes.What does it do for missing spaces
Output:   capitalizes.What does it do for missing spaces
Ideally, the output should have a space between the full stop and "What"

What is the best way to add this additional rule?

**Comment by myint** [comment]
`language-check` is a Python interface to [LanguageTool](https://www.languagetool.org) so I think additional checks would need to be added there.
