### ISSUE TITLE
Missing Grammar check rules- does not delete multiple commas

### ISSUE THREAD

**Issue by nnayar** [myint/language-check#49]
I am testing out for a few grammatical error conditions and not getting the desired results:

Repeated Commas:
Example:
Input:    How does it handle multiple commas,,,  , , ,.
Output: How does it handle multiple commas,,,  , , ,.
Ideally, the output should delete the extra repeated commas

What is the best way to add this additional rule?

**Comment by myint** [comment]
`language-check` is a Python interface to [LanguageTool](https://www.languagetool.org) so I think additional checks would need to be added there.
